import CFLeanProof.GCAOutput

/-! # The model/computation boundary

The manuscript's model says that "a *step* of a process consists of a local
computation followed by at most one atomic (read or write) operation on a
register" (`main.tex`, §"Algorithms and executions").  A local computation is
therefore *one step*, whatever it costs.  `GCA.Protocol.advance` is faithful to
that: stages `2` and `5` — the candidate calculation of GCA line 4 and the
output calculation of GCA line 6 — each advance in a single scheduled step,
with no interface assumption, exactly as stages `0,1,3,4` are the four assumed
snapshot operations.

So the Lean development inherits the manuscript's own convention, and the trace
operators may legitimately be classical: `traceGLB`, `traceLUB`,
`compatiblePart`, `gcaCandidate` and `gcaOutput` are `noncomputable`
mathematical specifications of those steps, not claims about running code.

What this module adds is the *name* of what must be effective if one wants to
read "implementation" in the stronger, executable sense.  `LocalCompute` is that
interface: a small bundle of operations with correctness specifications, the
computational counterpart of `Family.SnapshotWaitFree`.  Three facts are proved
about it.

* It **adds no mathematics**: each field is pinned down by its specification
  (`glb_eq`, `lub_eq`), because greatest lower and least upper bounds of traces
  are unique.
* It is **sufficient**: the two classical GCA stages factor through it
  (`compatiblePart_eq`, `candidate_eq`, `output_eq`), so nothing else in
  Algorithms 1–3 needs to be made effective.  In particular the algorithms
  never test `Object.Conflict`: no constructor of `WeakUniversal.Step` or
  `HelpingUniversal.Step` mentions it.  Conflict is a *specification* relation,
  used to state §3's progress conditions, not a line of pseudocode.
* It is **consistent** (`classical`), and its independence test is genuinely
  decidable whenever the object has finitely many states
  (`FiniteState.decidableIndependent`) — which is where the trace monoid, and
  hence every operator above, is actually rooted.
-/
namespace ConflictFreedom.Object
variable {State Op Response : Type} (obj : Object State Op Response)

/-! ### Pair compatibility is the two-element case of finite compatibility -/

variable [DecidableEq Op]

omit [DecidableEq Op] in
theorem pairCompatible_iff_compatible (s t : obj.Trace) :
    obj.PairCompatible s t ↔ obj.Compatible (fun u => u ∈ [s, t]) := by
  constructor
  · rintro ⟨u, hs, ht⟩
    refine ⟨u, ?_⟩
    intro v hv
    rcases List.mem_cons.mp hv with rfl | hv
    · exact hs
    · rcases List.mem_cons.mp hv with rfl | hv
      · exact ht
      · cases hv
  · rintro ⟨u, hu⟩
    exact ⟨u, hu s (List.mem_cons_self ..), hu t (List.mem_cons_of_mem _ (List.mem_cons_self ..))⟩

/-! ### The interface -/

/-- **The local computations Algorithms 1–3 perform between shared-memory
accesses**, bundled as data with their specifications.

Everything else the pseudocode evaluates locally is already computable from
`DecidableEq Op`: `traceCount` and `traceResponses` are `Quotient.lift`s of
`List.count` and of the response fold, `traceAppend` is list concatenation, and
the maximum of a collect compares round numbers.  What is not computable from
`DecidableEq Op` alone is exactly this list: the trace monoid depends on the
independence relation, and the lattice operations depend on the monoid. -/
structure LocalCompute where
  /-- Deciding independence.  The trace quotient is generated by swaps of
  independent operations, so this is the root of every operator below. -/
  independent : Op → Op → Bool
  independent_iff : ∀ a b, independent a b = true ↔ obj.Independent a b
  /-- Deciding whether a finite set of traces has a common extension: the test
  in GCA line 6, and, in its two-element case, the conflict test of line 3. -/
  compatible : List obj.Trace → Bool
  compatible_iff : ∀ S, compatible S = true ↔ obj.Compatible (fun s => s ∈ S)
  /-- `⊓` of a nonempty finite family: GCA lines 3 and 6. -/
  glb : obj.Trace → List obj.Trace → obj.Trace
  glb_spec : ∀ s S, obj.IsGLB (fun t => t ∈ s :: S) (glb s S)
  /-- `⊔` of a compatible finite family: GCA line 4. -/
  lub : List obj.Trace → obj.Trace
  lub_spec : ∀ S, obj.Compatible (fun t => t ∈ S) → obj.IsLUB (fun t => t ∈ S) (lub S)

namespace LocalCompute
variable {obj} (e : LocalCompute obj)

/-- Pair compatibility, from the finite test. -/
def pairCompatible (s t : obj.Trace) : Bool := e.compatible [s, t]

omit [DecidableEq Op] in
theorem pairCompatible_iff (s t : obj.Trace) :
    e.pairCompatible s t = true ↔ obj.PairCompatible s t := by
  rw [pairCompatible, e.compatible_iff, obj.pairCompatible_iff_compatible]

/-! ### The interface adds no mathematics: its fields are forced -/

/-- The supplied `glb` is *the* greatest lower bound, so the interface is a
refinement of the classical definition rather than an extra assumption. -/
theorem glb_eq (s : obj.Trace) (S : List obj.Trace) :
    e.glb s S = obj.traceGLB (fun t => t ∈ s :: S) ⟨s, List.mem_cons_self ..⟩ :=
  obj.glb_unique (e.glb_spec s S) (obj.traceGLB_spec _ _)

theorem lub_eq (S : List obj.Trace) (hc : obj.Compatible (fun t => t ∈ S)) :
    e.lub S = obj.traceLUB (fun t => t ∈ S) hc :=
  obj.lub_unique (e.lub_spec S hc) (obj.traceLUB_spec _ _)

/-! ### The interface is sufficient: GCA's two classical stages factor through it -/

/-- GCA line 3, computed: replace `s` by the meet of `s` with the inputs it
conflicts with. -/
def compatiblePart (s : obj.Trace) (S : List obj.Trace) : obj.Trace :=
  e.glb s (S.filter (fun t => ! e.pairCompatible s t))

omit [DecidableEq Op] in
theorem conflictNeighborhood_eq (s : obj.Trace) (S : List obj.Trace) :
    (fun t => t ∈ s :: S.filter (fun t => ! e.pairCompatible s t))
      = obj.ConflictNeighborhood (fun u => u ∈ S) s := by
  funext t
  apply propext
  rw [List.mem_cons, List.mem_filter]
  constructor
  · rintro (rfl | ⟨ht, hp⟩)
    · exact Or.inl rfl
    · refine Or.inr ⟨ht, ?_⟩
      intro hc
      rw [Bool.not_eq_true'] at hp
      exact absurd ((e.pairCompatible_iff s t).mpr hc) (by simp [hp])
  · rintro (rfl | ⟨ht, hc⟩)
    · exact Or.inl rfl
    · refine Or.inr ⟨ht, ?_⟩
      cases hb : e.pairCompatible s t with
      | false => simp
      | true => exact absurd ((e.pairCompatible_iff s t).mp hb) hc

theorem compatiblePart_eq (s : obj.Trace) (S : List obj.Trace) :
    e.compatiblePart s S = obj.compatiblePart (fun u => u ∈ S) s := by
  refine obj.glb_unique ?_ (obj.compatiblePart_spec _ s)
  rw [← e.conflictNeighborhood_eq s S]
  exact e.glb_spec s _

/-- GCA line 4, computed. -/
def candidate (S : List obj.Trace) : obj.Trace :=
  e.lub (S.map (fun s => e.compatiblePart s S))

theorem candidate_eq (S : List obj.Trace) : e.candidate S = obj.gcaCandidate S := by
  have hmap : S.map (fun s => e.compatiblePart s S)
      = S.map (obj.compatiblePart (fun u => u ∈ S)) := by
    apply List.map_congr_left
    intro s _
    exact e.compatiblePart_eq s S
  refine obj.lub_unique ?_ (obj.gcaCandidate_spec S)
  rw [candidate, hmap]
  exact e.lub_spec _ (obj.compatiblePart_family S)

/-- The flagged candidates of GCA line 6, computed. -/
def flagged (B : List (List obj.Trace)) : List obj.Trace :=
  (B.filter (fun S => e.compatible S)).map e.candidate

theorem flagged_eq (B : List (List obj.Trace)) : e.flagged B = obj.gcaFlagged B := by
  classical
  have hfil : B.filter (fun S => e.compatible S)
      = B.filter (fun S => decide (obj.Compatible (fun s => s ∈ S))) := by
    apply List.filter_congr
    intro S _
    cases hb : e.compatible S with
    | true =>
        have := (e.compatible_iff S).mp hb
        simp [this]
    | false =>
        have hn : ¬ obj.Compatible (fun s => s ∈ S) := by
          intro hc
          exact absurd ((e.compatible_iff S).mpr hc) (by simp [hb])
        simp [hn]
  have hmap : ∀ l : List (List obj.Trace), l.map e.candidate = l.map obj.gcaCandidate :=
    fun l => List.map_congr_left (fun S _ => e.candidate_eq S)
  rw [flagged, hfil, hmap]
  rfl

/-- GCA line 6, computed. -/
def output (own : List obj.Trace) (B : List (List obj.Trace)) : obj.Trace :=
  match e.flagged B with
  | [] => e.candidate own
  | s :: rest => e.glb s rest

theorem output_eq (own : List obj.Trace) (B : List (List obj.Trace)) :
    e.output own B = obj.gcaOutput own B := by
  classical
  unfold output gcaOutput
  cases hf : e.flagged B with
  | nil =>
      have hne : ¬ ∃ s, s ∈ obj.gcaFlagged B := by
        rintro ⟨s, hs⟩
        rw [← e.flagged_eq, hf] at hs
        cases hs
      rw [dite_eq_right hne]
      exact e.candidate_eq own
  | cons s rest =>
      have hne : ∃ t, t ∈ obj.gcaFlagged B := by
        refine ⟨s, ?_⟩
        rw [← e.flagged_eq, hf]
        exact List.mem_cons_self ..
      rw [dite_eq_left hne]
      have hgf : obj.gcaFlagged B = s :: rest := (e.flagged_eq B).symm.trans hf
      refine obj.glb_unique (e.glb_spec s rest) ⟨?_, ?_⟩
      · intro t ht
        exact (obj.traceGLB_spec _ hne).1 t (by rw [hgf]; exact ht)
      · intro l hl
        exact (obj.traceGLB_spec _ hne).2 l
          (fun t ht => hl t (by rw [← hgf]; exact ht))

end LocalCompute

/-! ### The interface is consistent -/

open Classical in
/-- Every object has a `LocalCompute` *mathematically*: the specifications are
satisfiable, so results assuming the interface are not vacuous.  This instance
is `noncomputable` on purpose — it is the statement that the boundary is a
boundary of effectivity, not of mathematics. -/
noncomputable def LocalCompute.classical : LocalCompute obj where
  independent := fun a b => decide (obj.Independent a b)
  independent_iff := fun a b => by simp
  compatible := fun S => decide (obj.Compatible (fun s => s ∈ S))
  compatible_iff := fun S => by simp
  glb := fun s S => obj.traceGLB (fun t => t ∈ s :: S) ⟨s, List.mem_cons_self ..⟩
  glb_spec := fun s S => obj.traceGLB_spec _ _
  lub := fun S =>
    if h : obj.Compatible (fun t => t ∈ S) then obj.traceLUB (fun t => t ∈ S) h
    else obj.emptyTrace
  lub_spec := fun S h => by rw [dite_eq_left h]; exact obj.traceLUB_spec _ _

/-! ### Where effectivity actually has to come from

The trace monoid is generated by swaps of *independent* operations, so an
effective monoid needs an effective independence test.  `Independent` quantifies
over every state, so `DecidableEq Op` is not enough; but an object with finitely
many states — the usual case for a sequential specification given as an
automaton, which is how `main.tex` presents `A = (Q, q₀, O, R, σ)` — supplies
it outright. -/

/-- A finite state space, presented as an enumeration. -/
structure FiniteState (State : Type) where
  enum : List State
  complete : ∀ q, q ∈ enum

namespace FiniteState

/-- Commutation at a fixed state is a conjunction of three equalities. -/
def decidableCommuteAt [DecidableEq State] [DecidableEq Response]
    (obj : Object State Op Response) (a b : Op) (q : State) :
    Decidable (obj.CommuteAt a b q) := by
  unfold Object.CommuteAt
  infer_instance

/-- **Independence is decidable for a finite-state object**, hence so is
`Object.Conflict`. -/
def decidableIndependent [DecidableEq State] [DecidableEq Response]
    (fs : FiniteState State) (obj : Object State Op Response) (a b : Op) :
    Decidable (obj.Independent a b) := by
  letI := fun q => decidableCommuteAt obj a b q
  refine decidable_of_iff (∀ q ∈ fs.enum, obj.CommuteAt a b q) ?_
  constructor
  · intro h q; exact h q (fs.complete q)
  · intro h q _; exact h q

/-- On a finite-state object, conflict is decidable. -/
def decidableConflict [DecidableEq State] [DecidableEq Response]
    (fs : FiniteState State) (obj : Object State Op Response) (a b : Op) :
    Decidable (obj.Conflict a b) := by
  letI := fs.decidableIndependent obj a b
  exact decidable_of_iff (¬ obj.Independent a b)
    (by rw [obj.independent_iff_not_conflict]; exact Classical.not_not)

/-- The independence test a `LocalCompute` needs, for a finite-state object:
a genuine Boolean decision procedure, not a classical `decide`. -/
def independentTest [DecidableEq State] [DecidableEq Response]
    (fs : FiniteState State) (obj : Object State Op Response) (a b : Op) : Bool :=
  @decide _ (fs.decidableIndependent obj a b)

omit [DecidableEq Op] in
theorem independentTest_iff [DecidableEq State] [DecidableEq Response]
    (fs : FiniteState State) (obj : Object State Op Response) (a b : Op) :
    fs.independentTest obj a b = true ↔ obj.Independent a b := by
  letI := fs.decidableIndependent obj a b
  exact decide_eq_true_iff

end FiniteState
end ConflictFreedom.Object
