import Std

/-! Sequential specifications and the response-sensitive conflict relation (§3.1). -/
namespace ConflictFreedom

/-- A sequential object `(Q, q₀, O, R, σ)`: an initial state, and a transition
that maps an operation and a state to a response and the next state. -/
structure Object (State Op Response : Type) where
  initial : State
  step : Op → State → Response × State

namespace Object
variable {State Op Response : Type} (obj : Object State Op Response)

/-- Both responses and the final state must agree; equality of final states alone
is insufficient for the paper's notion of commutation. -/
def CommuteAt (a b : Op) (q : State) : Prop :=
  (obj.step a q).1 = (obj.step a (obj.step b q).2).1 ∧
  (obj.step b (obj.step a q).2).1 = (obj.step b q).1 ∧
  (obj.step b (obj.step a q).2).2 = (obj.step a (obj.step b q).2).2

/-- `a` and `b` commute at every state. -/
def Independent (a b : Op) : Prop := ∀ q, obj.CommuteAt a b q

/-- The conflict relation `a ≍ b`: `a` and `b` fail to commute at some state. -/
def Conflict (a b : Op) : Prop := ∃ q, ¬ obj.CommuteAt a b q

theorem commuteAt_symm {a b : Op} {q : State}
    (h : obj.CommuteAt a b q) : obj.CommuteAt b a q :=
  ⟨h.2.1.symm, h.1.symm, h.2.2.symm⟩

theorem independent_symm {a b : Op} (h : obj.Independent a b) :
    obj.Independent b a := fun q => obj.commuteAt_symm (h q)

theorem conflict_symm {a b : Op} (h : obj.Conflict a b) : obj.Conflict b a := by
  obtain ⟨q, hq⟩ := h
  exact ⟨q, fun h => hq (obj.commuteAt_symm h)⟩

theorem independent_iff_not_conflict (a b : Op) :
    obj.Independent a b ↔ ¬ obj.Conflict a b := by
  classical
  simp only [Independent, Conflict, not_exists, Classical.not_not]

/-- The state reached by running a schedule from `q`. -/
def finalState : List Op → State → State
  | [], q => q
  | a :: s, q => finalState s (obj.step a q).2

/-- Responses indexed by occurrence number of a fixed operation, rather than by
position in a representative schedule. -/
def responses [DecidableEq Op] (target : Op) : List Op → State → List Response
  | [], _ => []
  | a :: s, q =>
      (if a = target then [(obj.step a q).1] else []) ++
        responses target s (obj.step a q).2

theorem finalState_append (s t : List Op) (q : State) :
    obj.finalState (s ++ t) q = obj.finalState t (obj.finalState s q) := by
  induction s generalizing q with
  | nil => rfl
  | cons a s ih => exact ih _

theorem responses_append [DecidableEq Op] (target : Op) (s t : List Op) (q : State) :
    obj.responses target (s ++ t) q =
      obj.responses target s q ++ obj.responses target t (obj.finalState s q) := by
  induction s generalizing q with
  | nil => rfl
  | cons a s ih => simp [responses, finalState, ih, List.append_assoc]

/-- Trace equivalence generated by adjacent independent swaps. Its equivalence
with the paper's conflicting-occurrence order presentation is
`traceEq_iff_labeledOccurrenceEq` (`TraceOccurrences.lean`). -/
inductive TraceEq : List Op → List Op → Prop
  | refl (s) : TraceEq s s
  | swap (x y : List Op) (a b : Op) (h : obj.Independent a b) :
      TraceEq (x ++ a :: b :: y) (x ++ b :: a :: y)
  | symm {s t} : TraceEq s t → TraceEq t s
  | trans {s t u} : TraceEq s t → TraceEq t u → TraceEq s u

theorem traceEq_semantics [DecidableEq Op] {s t : List Op} (h : obj.TraceEq s t) :
    ∀ q, obj.finalState s q = obj.finalState t q ∧
      ∀ target, obj.responses target s q = obj.responses target t q := by
  induction h with
  | refl s => exact fun _ => ⟨rfl, fun _ => rfl⟩
  | symm h ih => exact fun q => ⟨(ih q).1.symm, fun o => ((ih q).2 o).symm⟩
  | trans h₁ h₂ ih₁ ih₂ =>
      exact fun q => ⟨(ih₁ q).1.trans (ih₂ q).1,
        fun o => ((ih₁ q).2 o).trans ((ih₂ q).2 o)⟩
  | swap x y a b h =>
      intro q
      have hc := h (obj.finalState x q)
      constructor
      · simp only [finalState_append, finalState]
        rw [hc.2.2]
      · intro target
        simp only [responses_append, responses]
        rw [hc.1, hc.2.1, hc.2.2]
        by_cases ha : a = target <;> by_cases hb : b = target
        · subst a; subst b
          have hr := (h (obj.finalState x q)).1
          simp [hr]
        · simp [ha, hb]
        · simp [ha, hb]
        · simp [ha, hb]

theorem traceEq_append_left (x : List Op) {s t : List Op} (h : obj.TraceEq s t) :
    obj.TraceEq (x ++ s) (x ++ t) := by
  induction h with
  | refl s => exact TraceEq.refl _
  | swap y z a b h =>
      simpa only [List.append_assoc] using (TraceEq.swap (x ++ y) z a b h)
  | symm h ih => exact TraceEq.symm ih
  | trans h₁ h₂ ih₁ ih₂ => exact TraceEq.trans ih₁ ih₂

theorem traceEq_append_right (x : List Op) {s t : List Op} (h : obj.TraceEq s t) :
    obj.TraceEq (s ++ x) (t ++ x) := by
  induction h with
  | refl s => exact TraceEq.refl _
  | swap y z a b h =>
      simpa only [List.append_assoc, List.cons_append] using (TraceEq.swap y (z ++ x) a b h)
  | symm h ih => exact TraceEq.symm ih
  | trans h₁ h₂ ih₁ ih₂ => exact TraceEq.trans ih₁ ih₂

theorem traceEq_length {s t : List Op} (h : obj.TraceEq s t) : s.length = t.length := by
  induction h with
  | refl s => rfl
  | swap x y a b h => simp
  | symm h ih => exact ih.symm
  | trans h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Trace equivalence, as a setoid on schedules. -/
def traceSetoid : Setoid (List Op) where
  r := obj.TraceEq
  iseqv := ⟨TraceEq.refl, TraceEq.symm, TraceEq.trans⟩

/-- Traces: schedules up to swapping adjacent independent operations. -/
def Trace := Quotient obj.traceSetoid

/-- Concatenation of traces, `s · t`. -/
def traceAppend (s t : obj.Trace) : obj.Trace :=
  Quotient.liftOn₂ s t (fun x y => Quotient.mk obj.traceSetoid (x ++ y))
    (fun _a b c _d hab hcd => Quotient.sound
      (TraceEq.trans (obj.traceEq_append_right b hab) (obj.traceEq_append_left c hcd)))

/-- The number of operations in a trace. -/
def traceLength : obj.Trace → Nat :=
  Quotient.lift List.length (fun _ _ h => obj.traceEq_length h)

theorem traceAppend_assoc (s t u : obj.Trace) :
    obj.traceAppend (obj.traceAppend s t) u = obj.traceAppend s (obj.traceAppend t u) := by
  induction s using Quotient.inductionOn with | h s =>
    induction t using Quotient.inductionOn with | h t =>
      induction u using Quotient.inductionOn with | h u =>
        exact congrArg (Quotient.mk obj.traceSetoid) (List.append_assoc s t u)

/-- The per-operation response sequence is well-defined on traces. -/
def traceResponses [DecidableEq Op] (target : Op) (q : State) : obj.Trace → List Response :=
  Quotient.lift (fun s => obj.responses target s q)
    (fun _ _ h => (obj.traceEq_semantics h q).2 target)

/-- Trace prefix, stated using representatives and concatenation. -/
def TracePrefix (s t : obj.Trace) : Prop :=
  ∃ x y : List Op, Quotient.mk obj.traceSetoid x = s ∧
    Quotient.mk obj.traceSetoid (x ++ y) = t

/-- Response-sequence form of Lemma RetTracePrefix. Thus every existing
occurrence retains its response when a trace is extended. -/
theorem traceResponses_prefix [DecidableEq Op] {s t : obj.Trace}
    (h : obj.TracePrefix s t) (target : Op) (q : State) :
    ∃ suffix, obj.traceResponses target q t = obj.traceResponses target q s ++ suffix := by
  obtain ⟨x, y, rfl, rfl⟩ := h
  exact ⟨obj.responses target y (obj.finalState x q), obj.responses_append target x y q⟩

end Object
end ConflictFreedom
